// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// source: messages-ckb.proto
// DO NOT EDIT
import { type Static, Type } from '@trezor/schema-utils';

export enum Enum_CKBTxRequestType {
    TXINPUT = 0,
    TXOUTPUT = 1,
    TXCELLDEP = 2,
    TXFINISHED = 3,
}

export type EnumEnum_CKBTxRequestType = Static<typeof EnumEnum_CKBTxRequestType>;
export const EnumEnum_CKBTxRequestType = Type.Enum(Enum_CKBTxRequestType);

export type CKBTxRequestType = Static<typeof CKBTxRequestType>;
export const CKBTxRequestType = Type.KeyOfEnum(Enum_CKBTxRequestType, {
    $id: 'CKBTxRequestType',
});

export type CKBGetAddress = Static<typeof CKBGetAddress>;
export const CKBGetAddress = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        show_display: Type.Optional(Type.Boolean()),
        network: Type.Optional(Type.String()),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'CKBGetAddress' },
);

export type CKBAddress = Static<typeof CKBAddress>;
export const CKBAddress = Type.Object(
    {
        address: Type.String(),
    },
    { $id: 'CKBAddress' },
);

export type CKBCellInput = Static<typeof CKBCellInput>;
export const CKBCellInput = Type.Object(
    {
        previous_output_tx_hash: Type.String(),
        previous_output_index: Type.Number(),
        since: Type.Optional(Type.Uint()),
    },
    { $id: 'CKBCellInput' },
);

export type CKBCellOutput = Static<typeof CKBCellOutput>;
export const CKBCellOutput = Type.Object(
    {
        capacity: Type.Uint(),
        lock_code_hash: Type.String(),
        lock_hash_type: Type.Number(),
        lock_args: Type.String(),
        type_code_hash: Type.Optional(Type.String()),
        type_hash_type: Type.Optional(Type.Number()),
        type_args: Type.Optional(Type.String()),
        data: Type.Optional(Type.String()),
    },
    { $id: 'CKBCellOutput' },
);

export type CKBCellDep = Static<typeof CKBCellDep>;
export const CKBCellDep = Type.Object(
    {
        tx_hash: Type.String(),
        index: Type.Number(),
        dep_type: Type.Number(),
    },
    { $id: 'CKBCellDep' },
);

export type CKBSignTx = Static<typeof CKBSignTx>;
export const CKBSignTx = Type.Object(
    {
        address_n: Type.Array(Type.Number()),
        network: Type.Optional(Type.String()),
        inputs_count: Type.Number(),
        outputs_count: Type.Number(),
        cell_deps_count: Type.Optional(Type.Number()),
        fee: Type.Optional(Type.Uint()),
        chunkify: Type.Optional(Type.Boolean()),
    },
    { $id: 'CKBSignTx' },
);

export type CKBTxRequestDetails = Static<typeof CKBTxRequestDetails>;
export const CKBTxRequestDetails = Type.Object(
    {
        request_index: Type.Optional(Type.Number()),
    },
    { $id: 'CKBTxRequestDetails' },
);

export type CKBTxRequestSerialized = Static<typeof CKBTxRequestSerialized>;
export const CKBTxRequestSerialized = Type.Object(
    {
        signature: Type.Optional(Type.String()),
        tx_hash: Type.Optional(Type.String()),
    },
    { $id: 'CKBTxRequestSerialized' },
);

export type CKBTxRequest = Static<typeof CKBTxRequest>;
export const CKBTxRequest = Type.Object(
    {
        request_type: Type.Optional(CKBTxRequestType),
        details: Type.Optional(CKBTxRequestDetails),
        serialized: Type.Optional(CKBTxRequestSerialized),
    },
    { $id: 'CKBTxRequest' },
);

export type CKBTxAckInput = Static<typeof CKBTxAckInput>;
export const CKBTxAckInput = Type.Object(
    {
        input: Type.Optional(CKBCellInput),
    },
    { $id: 'CKBTxAckInput' },
);

export type CKBTxAckOutput = Static<typeof CKBTxAckOutput>;
export const CKBTxAckOutput = Type.Object(
    {
        output: Type.Optional(CKBCellOutput),
    },
    { $id: 'CKBTxAckOutput' },
);

export type CKBTxAckCellDep = Static<typeof CKBTxAckCellDep>;
export const CKBTxAckCellDep = Type.Object(
    {
        cell_dep: Type.Optional(CKBCellDep),
    },
    { $id: 'CKBTxAckCellDep' },
);
